### ISSUE TITLE
Revisit the Split with SonataClassificationBundle

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataMediaBundle#1978]
## Feature Request

When we removed the coupling with SonataClassificationBundle we let some methods related to the Categories and Contexts.

We should remove them or provide a clearer api to avoid having to do calls like `method_exists($media, 'setCategory')`

It was saw here: https://github.com/sonata-project/SonataMediaBundle/pull/1975

**Comment by VincentLanglet** [comment]
Adding the `SonataClassificationBundle` to the dev dependency could solve everything isn't it ?
The static analysis won't complain and the conflict will be tested.

**Comment by jordisala1991** [comment]
That creates a cyclic dependency that we wanted to avoid

**Comment by jordisala1991** [comment]
And it won't fix all the problems

**Comment by VincentLanglet** [comment]
Every conflict should be added to the dev dependency in order to test that the allowed version is working.

So the real issue to me is that MediaBundle is using ClassificationBundle and ClassificationBundle also use MediaBundle.
We should decide which one should use the other and then move some code from one to another.

I see the following code 
```
use Sonata\ClassificationBundle\...
```
in the mediaBundle. But I don't see any
```
use Sonata\MediaBundle\...
```
in the ClassificationBundle. It was removed from master with https://github.com/sonata-project/SonataClassificationBundle/pull/196.

So IMHO, the mediaBundle should have the ClassificationBundle in his dev-dependency, if we're requiring the dev branch, we shouldn't have circular dependendy, isn't it ?

It would also mean that we should maybe work on ClassificationBundle v4 before MediaBundle v4

**Comment by jordisala1991** [comment]
> in the ClassificationBundle. It was removed from master with sonata-project/SonataClassificationBundle#196.

If that is the case it can be done.

> It would also mean that we should maybe work on ClassificationBundle v4 before MediaBundle v4

That is a problem for me, the time is very limited and I don't know anything about ClassificationBundle to start again with that bundle.

IMHO if we want to move this one forward, I would prefer to do the integration with classificationBundle once the v4 branch is prepared (or as the last step).

**Comment by VincentLanglet** [comment]
We can add a dependency on Classification@dev to try to solve this until we work on the v4.

But we shouldn't release the v4 of MediaBundle before the v4 of Classification, because if a change/need in the Classification v4 require a BC-break in MediaBundle to keep the integration we'll be stuck.

Ping @sonata-project/contributors if someone wants to help and take the Classification v4 subject.

**Comment by jordisala1991** [comment]
If we add the dependency with master right now, we lose the sf 5.x support.

**Comment by wbloszyk** [comment]
Can we add `use_classification_bundle` parametr for it? By default false. User can use them if change it by own. It mean he/she have to add classificationBundle to composer by own too. Dependencies will be add to suggest. We can also test it by dev-kit.

**Comment by VincentLanglet** [comment]
> Can we add `use_classification_bundle` parameter for it?

This is not needed, the rule is already if you want to use the classification bundle, you have to add it.
The issue is more static analysis related, we're using method from ClassificationBundle without requiring it (at least in the dev-dependencies).

As long as we don't require the classification bundle, we cannot be sure our classification-related code is fully functionnal.

IMHO, the plan is
- Adding SF5/Twig3 support to Classification
- Adding SonataClassificationBundle to the require-dev of SonataMedia.

**Comment by VincentLanglet** [comment]
I've started https://github.com/sonata-project/SonataClassificationBundle/pull/678, not sure it will be too hard.
