### ISSUE TITLE
FileProvider tries to delete not empty dir

### ISSUE THREAD

**Issue by PoisonousJohn** [sonata-project/SonataMediaBundle#247]
I'm trying to update an avatar image and getting error

``` php
            // Save avatar
            $media->setName($filename);
            $media->setEnabled(true);
            $media->setBinaryContent($filename);
            $media->setContext('avatar');
            $media->setProviderName('sonata.media.provider.image');
            $mediaManager = $this->get('sonata.media.manager.media');


            // Attach avatar
            $user->setPhoto($media);
            $mediaManager->save($media);
```

Warning: rmdir(/Users/user/git/sf-2.1-build/data/uploads/media/avatar/0001/01) [<a href='function.rmdir'>function.rmdir</a>]: Directory not empty in /Users/user/git/sf-2.1-build/repo/dev/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/Local.php line 128

stacktrace:

```
at ErrorHandler ->handle ('2', 'rmdir(/Users/user/git/sf-2.1-build/data/uploads/media/avatar/0001/01) [<a href='function.rmdir'>function.rmdir</a>]: Directory not empty', '/Users/user/git/sf-2.1-build/repo/dev/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/Local.php', '128', array('key' => 'avatar/0001/01/')) 

at rmdir ('/Users/user/git/sf-2.1-build/data/uploads/media/avatar/0001/01') 
in /Users/user/git/sf-2.1-build/repo/dev/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/Local.php at line 128 

at Local ->delete ('avatar/0001/01/') 
in /Users/user/git/sf-2.1-build/repo/dev/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php at line 148    

at Filesystem ->delete ('avatar/0001/01/') 
in /Users/user/git/sf-2.1-build/repo/dev/vendor/sonata-project/media-bundle/Sonata/MediaBundle/Provider/FileProvider.php at line 133 
```

**Comment by DelphineGx** [comment]
I followed @VincentChalnot advice but I figured out that it's not working..

I think there is a mistake so I added in my Media.php entity:

```php

    if(!$this->providerReference && $this->previousProviderReference){
            $this->providerReference = $this->previousProviderReference;
        }

```

And everything works ! unlink, replace file, Etc.

**Comment by remyflier** [comment]
Hi @DelphineGx, can you explain why that piece of code works. It makes no sense to me. 

$this->previousProviderReference is there to process the old file when new binaryContent is inserted. What you do is set the providerReference of the current/new file to the previousProviderReference. 
That's the opposite of what should happen, in my opinion. 

The solution of @VincentChalnot solved some issues for me, but today we had a related issue. 
When updating a new media entity which was already flushed  would also result in the problem of gaufrette trying to remove a directory. Origin of this problem is the empty providerReference which results in a wrong filesystem path.

When a file is flushed the binaryContent should be emptied. When it's not the next part is executed:

    if (!$media->getBinaryContent() instanceof \SplFileInfo) {
        return;
    }

    // Delete the current file from the FS
    $oldMedia = clone $media;
    $oldMedia->setProviderReference($media->getPreviousProviderReference());

    $path = $this->getReferenceImage($oldMedia);

    if ($this->getFilesystem()->has($path)) {
        $this->getFilesystem()->delete($path);
    }

Here providerReference is set using previousProviderReference. Because the file is not replaced (but binaryContent still holds the original upload) previousProviderReference is empty. Next the path will only hold the path to the directory and the filesystem tries to delete the directory.

I added a PostPersist Listener which will empty binaryContent after storing the file. This will solve the problem. It seems to me this is a bug.

    class MediaSubscriber implements EventSubscriber
    {
        /**
         * Returns an array of events this subscriber wants to listen to.
         * @return array
         */
        public function getSubscribedEvents()
        {
            return array('postPersist', -100);
        }
    
        /**
         * @param LifecycleEventArgs $args
         */
        public function postPersist(LifecycleEventArgs $args)
        {
            $entity = $args->getEntity();
    
            if ($entity instanceof Media) {
                // If we are here, the file must already be stored to the filesystem.
                // Empty binaryContent to prevent issues where the code assumes 
                // a newly uploaded file.
                $entity->setBinaryContent(null);
            }
        }
    }

And the service definition:

    services:
        application.sonata.media_bundle.event_handler.doctrine.media_subscriber:
            class: Application\Sonata\MediaBundle\EventHandler\Doctrine\MediaSubscriber
            tags:
                - { name: doctrine.event_subscriber }

**Comment by morille** [comment]
FYI this issue does not appear anymore in 2.4.x-dev

**Comment by Rmannn** [comment]
3 years after, same issues...

**Comment by morille** [comment]
@Rmannn Use the master version.

**Comment by MlleDelphine** [comment]
@remyflier : sorry for my huuuge late !

I was trying to remember what I had done ;p !

So, I did this trick because of `"orphanRemoval=true"`.
While you're updating picture, it will attach the new file to your Entity but.. It keeps old file.
I don't want to..
So I added "orphanRemoval=true"` and `"rmdir exception"` came too..

I am stuck with this again, don't know why.. "composer update" ? :@

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
