### ISSUE TITLE
Resizer per format

### ISSUE THREAD

**Issue by marcinziolo** [sonata-project/SonataMediaBundle#370]
Don't you think that resizer should be assigned to concrete formate in formats section ?

For example I would like to create two thumbnails with different resizer for one media object.

  formats:
    simple: { width: 100, height: 80, resizer: sonata.media.resizer.simple}
    exact_size:   { width: 200, height: 150, resizer: my.bundle.resizer.custom} //first crop and then resize in order to get 200x150 thumbnail

Now I can only assign resizer per all thumbnails what isn't sufficient for my requirements.

**Comment by aivus** [comment]
:+1:

**Comment by bertrandg** [comment]
:+1:

**Comment by djaney** [comment]
:+1:

**Comment by ruscon** [comment]
:+1:

**Comment by malenkiki** [comment]
It is logical and must have feature. I dont understand, that since 2013, it is not yet done.

**Comment by OskarStark** [comment]
> It is logical and must have feature. I dont understand, that since 2013, it is not yet done.

We are an Open-Source project and if you need it, you can provide a PR, thats how it works. If its not done yet, the needs seems to be NOT that "must have"....

**Comment by greg0ire** [comment]
@malenkiki if you want to understand, find out why _you_ didn't contribute it, then assume everyone had similar reasons.

**Comment by andreasschacht** [comment]
@OskarStark @greg0ire I agree that everybody should provide a solution instead of complaining about, but there was already a PR #423  for this. It was closed for a reason I can not follow...
It looks like, provide additional data in this place isn't a good solution at all for you. Or is there a chance to reopen this?

**Comment by greg0ire** [comment]
Hmmm I don't know if I understand the problem correctly because I don't use this bundle, so please tell me if I'm wrong:

- there are formats, that map to resizer services, that are called here: https://github.com/sonata-project/SonataMediaBundle/blob/d7c493472d15d352fd05835041100d67ddb7db8c/Thumbnail/FormatThumbnail.php#L82
- you would like to be able to call your own resizer service, but be able to pass it some more options.

In the case of the watermark, adding a watermark can't really be called "resizing", so maybe this is not the right abstraction?
This sounds awefully like a think the liipimaginebundle would be able to do, and we provide integration with it: https://github.com/sonata-project/SonataMediaBundle/blob/fabd14b939267ab9ef622963f14aed1cf26caa4c/Resources/doc/reference/extra.rst#liip-imagine-bundle-integration

It provides filters instead of resizers, so maybe use just that?

**Comment by andreasschacht** [comment]
@greg0ire Maybe the watermark example isn't the best one, but I'm talking about provide additional custom options in general in the formats for better support custom resizers. 
This PR #423 was just about provide some extra options for custom resizers, and was declined just because it was pointed to a bad example?

> In the case of the watermark, adding a watermark can't really be called "resizing", so maybe this is not the right abstraction?

The formats also provides additional informations like  'constraint', that's unrelated to "resizing". Also change quality and format can be seen as edge cases when thinking about a pure "resize" operation.

In my case, I want a flipped thumbnail (besides a "regular" one) in the same context. In my opinion, the possibiltiy to provide an additional flag that can be used in the `generate` method of a `ThumbnailInterface` implementation (like you pointed to) is the right abstraction. So there is a need and good reasons to provide additional information.

Solve this with the liipimaginebundle isn't a solution for me.

**Comment by greg0ire** [comment]
> The formats also provides additional informations like 'constraint', that's unrelated to "resizing"

I did not understand what this option is about. Do you know?

> Solve this with the liipimaginebundle isn't a solution for me.

Can you detail why not exactly? I am reluctant to have an equivalent of the liip bundle in this bundle, no need to duplicate efforts.

**Comment by andreasschacht** [comment]
@greg0ire 
I also didn't know the `constraint` option.

The main reason why liipimaginebundle doesn't work for me, that it doesn't generate thumbs on upload time. Instead you have to use a specific controller.

But that's not the point of the matter. I think PR #423 should be reopened, because there is a need for it.

**Comment by greg0ire** [comment]
> The main reason why liipimaginebundle doesn't work for me, that it doesn't generate thumbs on upload time. Instead you have to use a specific controller.

[There is a command to do that at any time you want](https://github.com/liip/LiipImagineBundle#resolve-with-the-console) (I do it asynchronously with rabbitmq, just after the upload).

Now let's say we want to do it in this bundle anyway. I think it would be acceptable to do the following:

- introduce a `FilterInterface`
- have the existing resizers implement it
- allow adding as many filters as you want to the `FormatThumbnail`
- by default, add a resizer filter
- change this piece of code: https://github.com/sonata-project/SonataMediaBundle/blob/d7c493472d15d352fd05835041100d67ddb7db8c/Thumbnail/FormatThumbnail.php#L82-L88
so that it does a foreach on each filter

But that sounds a lot like what the LiipImagineBundle does, so what's the point?

**Comment by andreasschacht** [comment]
Can't follow you. I just want provide some extra options per format a custom resizer or `ThumnailInterface` can use. That's 2 lines of code.

**Comment by greg0ire** [comment]
I understand your frustration, but this is a (very widely used) library, this is not a project. This means you don't do quick hacks in it. The extension points have to have some meaning. If you want to do a quick hack, just click the fork button, and use your fork in your project. If you want to do it properly... I described how to do it, but IMO, it will be more simple to use the bundle from liip, and it might be why it has been integrated with this bundle.

**Comment by andreasschacht** [comment]
I'm not frustated. Sorry, if it sounds like. I just want to know, like I already ask in my first comment, if it's a bad solution in general for you to provide more information in the `format` option. Or just the way PR #423  did it?
Would a solution like in the first comment https://github.com/sonata-project/SonataMediaBundle/issues/370#issue-17379782 work for you?
If so, I can implement it and create a PR.
I don't want to discuss if or why I should use or not the liipimaginebundle...

**Comment by greg0ire** [comment]
The solution in the first comment would make sense to me : it allows the hack to stay in your project instead of going to the library.

**Comment by lukepass** [comment]
Hello! Any news about this issue?
It could so much useful to set the resizer per context / format.

Putting the resizer at the provider level is almost useless because it's very uncommon to have square images everywhere.

Thanks.
