### ISSUE TITLE
Working with files

### ISSUE THREAD

**Issue by NeglectedGoldfish** [sonata-project/SonataMediaBundle#67]
Hi,

If I have a specific context that only uses the file provider, am I correct in saying that I still need to provide a 'formats' parameter in my config file?

If so, is there anything specific I should enter as I'm dealing with PDF files only in this instance.

Also, how do I render the path to this file from Twig?

Thanks,

Fish

**Comment by nlenkowski** [comment]
This issue should probably not be closed. I am in a situation in which the PDF files that are uploaded will be downloaded by users. Currently when they download the file they get a PDF with an sha1 filename instead of the original filename. It makes it confusing for the end user. If this issue has been resolved it would be great if someone can point me in the right direction. It would be best to maintain the original file name, or at the very least generating a filename that is more user friendly than an sha1.
