### ISSUE TITLE
how to override/modify edit form

### ISSUE THREAD

**Issue by estebannovo** [sonata-project/SonataMediaBundle#958]
Dear,

I'm trying to develop a new provider for the bundle SonataMediaBundle and now I need to modify the form, for example I need to add HTML attributes to the form, such as ID and also want to remove buttons from the Edit Form (Create and Edit, create and return to the list , create and add another), how do I do to change the edit form.

My final idea is to integrate Jquery plugins MultipleFileUpload
![2016-02-26_1219](https://cloud.githubusercontent.com/assets/3704157/13356313/60b6fe8e-dc83-11e5-8469-8526ce4d6952.png)

I am in the process created and I still have to post the images

I appreciate your help.

**Comment by estebannovo** [comment]
any idea?

**Comment by hanovruslan** [comment]
I guess in the documentation you will find that some usefull plugins already integrated in the sonata, but your exact problem (task) really just to customize which form as a service or data class suppose to be injected  in your provider. Right?

**Comment by estebannovo** [comment]
Right, that plugins?

**Comment by jordisala1991** [comment]
This issue is not related to media-bundle, but to admin-bundle. ATM there is no feature to remove those buttons, but you can always edit some templates and do a workaround.

There are probably some issues related to this on the admin-bundle, but I couldn’t find them. If you still have this issue, please open an issue on the admin-bundle (please, first search if there is anything similar there)

Closing.
