### ISSUE TITLE
Missing dependency? (twig/extensions)

### ISSUE THREAD

**Issue by philmoreau** [sonata-project/SonataMediaBundle#975]
I got this error after install :

[Symfony\Component\Debug\Exception\ClassNotFoundException]
Attempted to load class "Twig_Extensions_Extension_Text" from the global namespace.

So I installed "twig/extensions" :

composer require twig/extensions

It solved the problem. Could it be a requirement that is missing?

**Comment by OskarStark** [comment]
@greg0ire can you check that?

**Comment by greg0ire** [comment]
Sure. @feastofvermin , could we get a full stack trace, to see where the extension is called?

**Comment by jordisala1991** [comment]
It is required, but I dont remember where :P will try to find

**Comment by phansys** [comment]
`Twig_Extensions_Extension_Text` isn't referenced from the (current) latest stable release [3.20.1](https://github.com/sonata-project/SonataMediaBundle/tree/3.20.1). Maybe the usage was removed between this version and the version used when the issue was reported or maybe the problem was not originated in this package.
If somebody is able to confirm the issue still exists, please share details about the stack trace using the issue template.

I'm closing this issue now.
