### ISSUE TITLE
Admin context for images provider

### ISSUE THREAD

**Issue by MAXakaWIZARD** [sonata-project/SonataMediaBundle#980]
As I see, there is `admin` context for images provider. Where it comes from? Can it be turned off? In my case it causes in too many extra thumbnails.

**Comment by jordisala1991** [comment]
The admin context is used to display the thumbnails, I dont think it can be disabled, since it is necessary to display the images on the admin.

It only generates an extra image.

This seems more like an issue for Stackoverflow.

Closing. If you think this is something we should fix, please feel free to open another issue with your proposal.
